const express = require('express');
const app = express();
const PORT = 3000;

app.use('/attached_assets', express.static('/var/www/attached_assets'));

const html = `<!DOCTYPE html><html><head><title>Happy Baby Sleeping</title><script src="https://cdn.tailwindcss.com"></script><script>tailwind.config={theme:{extend:{colors:{'baby-blue':'#87CEEB','soft-pink':'#FFB6C1','mint':'#98FB98','cream':'#FFF8DC','soft-dark':'#2F4F4F','medium-gray':'#696969'}}}}</script></head><body class="bg-cream"><main><section class="relative overflow-hidden"><div class="absolute inset-0 bg-gradient-to-br from-baby-blue/20 via-soft-pink/10 to-mint/20"></div><div class="relative max-w-7xl mx-auto px-4 py-16"><div class="grid lg:grid-cols-2 gap-12 items-center"><div class="text-center lg:text-left"><h1 class="text-6xl font-bold text-soft-dark mb-8">Peaceful Nights for Your <span class="text-baby-blue">Little One</span></h1><p class="text-xl text-medium-gray mb-8">Expert sleep consulting for healthy sleep habits and family rest.</p><div class="grid md:grid-cols-3 gap-6"><div class="bg-baby-blue/10 p-6 rounded-2xl text-center border-2 border-baby-blue/20"><h3 class="text-xl font-bold text-baby-blue mb-4">Free Consultation</h3><p class="text-medium-gray mb-4">30-minute assessment</p><div class="text-3xl font-bold text-baby-blue">FREE</div></div><div class="bg-soft-pink/10 p-6 rounded-2xl text-center border-2 border-soft-pink/20"><h3 class="text-xl font-bold text-soft-pink mb-4">Complete Sleep Package</h3><p class="text-medium-gray mb-4">Full training and support</p><div class="text-3xl font-bold text-soft-pink">$299</div></div><div class="bg-mint/10 p-6 rounded-2xl text-center border-2 border-mint/20"><h3 class="text-xl font-bold text-mint mb-4">Newborn Care</h3><p class="text-medium-gray mb-4">Specialized infant care</p><div class="text-3xl font-bold text-mint">$199</div></div></div></div><div class="mt-8 lg:mt-0"><img src="/attached_assets/image_1751435091363.jpeg" alt="Peaceful baby sleeping" class="rounded-3xl shadow-2xl w-full"></div></div></div></section></main></body></html>`;

app.get('*', (req, res) => res.send(html));
app.listen(PORT, '0.0.0.0', () => console.log('🌙 BEAUTIFUL BABY WEBSITE ON PORT ' + PORT));