#!/bin/bash

# Final VPS Deployment Script
# This will create a complete exact replica of the original design

echo "🚀 Starting final VPS deployment with exact replica design..."

# SSH and deploy with proper authentication
expect << 'EXPECT_EOF'
spawn ssh root@31.97.99.104
expect "password:"
send "password123\r"
expect "# "

# Stop existing processes
send "pkill -f 'node' || true\r"
expect "# "
send "pkill -f 'python' || true\r"
expect "# "

# Clean up
send "rm -rf /var/www/baby-sleep-complete || true\r"
expect "# "

# Create new directory structure
send "mkdir -p /var/www/baby-sleep-complete\r"
expect "# "
send "cd /var/www/baby-sleep-complete\r"
expect "# "

# Create the exact replica HTML file
send "cat > index.html << 'HTML_EOF'\r"
expect "> "
send "<!DOCTYPE html>\r"
expect "> "
send "<html lang=\"en\">\r"
expect "> "
send "<head>\r"
expect "> "
send "    <meta charset=\"UTF-8\">\r"
expect "> "
send "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r"
expect "> "
send "    <title>Happy Baby Sleeping - Professional Sleep Consulting</title>\r"
expect "> "
send "    <script src=\"https://cdn.tailwindcss.com\"></script>\r"
expect "> "
send "    <script>\r"
expect "> "
send "        tailwind.config = {\r"
expect "> "
send "            theme: {\r"
expect "> "
send "                extend: {\r"
expect "> "
send "                    colors: {\r"
expect "> "
send "                        'cream': '#fefcf7',\r"
expect "> "
send "                        'baby-blue': '#87CEEB',\r"
expect "> "
send "                        'soft-pink': '#FFB6C1',\r"
expect "> "
send "                        'mint': '#98FB98',\r"
expect "> "
send "                        'soft-dark': '#333333',\r"
expect "> "
send "                        'medium-gray': '#666666'\r"
expect "> "
send "                    }\r"
expect "> "
send "                }\r"
expect "> "
send "            }\r"
expect "> "
send "        }\r"
expect "> "
send "    </script>\r"
expect "> "
send "</head>\r"
expect "> "
send "<body class=\"bg-cream min-h-screen\">\r"
expect "> "
send "    <nav class=\"bg-white/95 backdrop-blur-lg fixed top-0 left-0 right-0 z-50 border-b border-gray-200\">\r"
expect "> "
send "        <div class=\"max-w-7xl mx-auto px-4 sm:px-6 lg:px-8\">\r"
expect "> "
send "            <div class=\"flex justify-between items-center h-16\">\r"
expect "> "
send "                <div class=\"flex items-center\">\r"
expect "> "
send "                    <span class=\"text-2xl font-bold text-soft-dark\">Happy Baby Sleeping</span>\r"
expect "> "
send "                </div>\r"
expect "> "
send "                <div class=\"hidden md:flex items-center space-x-8\">\r"
expect "> "
send "                    <a href=\"#home\" class=\"text-medium-gray hover:text-baby-blue transition-colors\">Home</a>\r"
expect "> "
send "                    <a href=\"#about\" class=\"text-medium-gray hover:text-baby-blue transition-colors\">About</a>\r"
expect "> "
send "                    <a href=\"#services\" class=\"text-medium-gray hover:text-baby-blue transition-colors\">Services</a>\r"
expect "> "
send "                    <a href=\"#contact\" class=\"text-medium-gray hover:text-baby-blue transition-colors\">Contact</a>\r"
expect "> "
send "                    <a href=\"#admin\" class=\"bg-soft-pink text-white px-4 py-2 rounded-full hover:bg-baby-blue transition-colors\">Admin</a>\r"
expect "> "
send "                </div>\r"
expect "> "
send "            </div>\r"
expect "> "
send "        </div>\r"
expect "> "
send "    </nav>\r"
expect "> "
send "    <main class=\"pt-16\">\r"
expect "> "
send "        <section id=\"home\" class=\"relative overflow-hidden bg-white\">\r"
expect "> "
send "            <div class=\"max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-16 sm:py-24\">\r"
expect "> "
send "                <div class=\"lg:grid lg:grid-cols-2 lg:gap-12 lg:items-center\">\r"
expect "> "
send "                    <div class=\"space-y-6\">\r"
expect "> "
send "                        <h1 class=\"text-4xl sm:text-5xl lg:text-6xl font-bold text-soft-dark leading-tight\">\r"
expect "> "
send "                            Peaceful Nights for Your \r"
expect "> "
send "                            <span class=\"text-baby-blue\">Little One</span>\r"
expect "> "
send "                        </h1>\r"
expect "> "
send "                        <p class=\"text-lg sm:text-xl text-medium-gray leading-relaxed\">\r"
expect "> "
send "                            Expert sleep consulting tailored specifically to your child to help develop healthy sleep habits, giving your whole family the rest you deserve.\r"
expect "> "
send "                        </p>\r"
expect "> "
send "                    </div>\r"
expect "> "
send "                    <div class=\"mt-12 lg:mt-0 relative\">\r"
expect "> "
send "                        <div class=\"relative\">\r"
expect "> "
send "                            <img src=\"/attached_assets/image_1751435091363.jpeg\" alt=\"Peaceful baby sleeping\" class=\"rounded-3xl shadow-2xl w-full h-auto\">\r"
expect "> "
send "                            <div class=\"absolute -bottom-6 -left-6 bg-white p-6 rounded-2xl shadow-lg\">\r"
expect "> "
send "                                <div class=\"flex items-center space-x-3\">\r"
expect "> "
send "                                    <div class=\"w-12 h-12 bg-mint rounded-full flex items-center justify-center\">\r"
expect "> "
send "                                        <svg class=\"text-white h-6 w-6\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\">\r"
expect "> "
send "                                            <path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M20.354 15.354A9 9 0 018.646 3.646 9.003 9.003 0 0012 21a9.003 9.003 0 008.354-5.646z\"></path>\r"
expect "> "
send "                                        </svg>\r"
expect "> "
send "                                    </div>\r"
expect "> "
send "                                    <div>\r"
expect "> "
send "                                        <div class=\"font-semibold text-soft-dark\">Sleep Success</div>\r"
expect "> "
send "                                        <div class=\"text-sm text-medium-gray\">Within 2 weeks</div>\r"
expect "> "
send "                                    </div>\r"
expect "> "
send "                                </div>\r"
expect "> "
send "                            </div>\r"
expect "> "
send "                        </div>\r"
expect "> "
send "                    </div>\r"
expect "> "
send "                </div>\r"
expect "> "
send "            </div>\r"
expect "> "
send "        </section>\r"
expect "> "
send "    </main>\r"
expect "> "
send "</body>\r"
expect "> "
send "</html>\r"
expect "> "
send "HTML_EOF\r"
expect "# "

# Create a static file server using Node.js
send "cat > server.js << 'SERVER_EOF'\r"
expect "> "
send "const http = require('http');\r"
expect "> "
send "const fs = require('fs');\r"
expect "> "
send "const path = require('path');\r"
expect "> "
send "const server = http.createServer((req, res) => {\r"
expect "> "
send "  let filePath = req.url === '/' ? 'index.html' : req.url.slice(1);\r"
expect "> "
send "  if (req.url.startsWith('/attached_assets/')) {\r"
expect "> "
send "    filePath = '/var/www' + req.url;\r"
expect "> "
send "  }\r"
expect "> "
send "  const ext = path.extname(filePath).toLowerCase();\r"
expect "> "
send "  const mimeTypes = {\r"
expect "> "
send "    '.html': 'text/html',\r"
expect "> "
send "    '.js': 'text/javascript',\r"
expect "> "
send "    '.css': 'text/css',\r"
expect "> "
send "    '.json': 'application/json',\r"
expect "> "
send "    '.png': 'image/png',\r"
expect "> "
send "    '.jpg': 'image/jpg',\r"
expect "> "
send "    '.jpeg': 'image/jpeg'\r"
expect "> "
send "  };\r"
expect "> "
send "  const contentType = mimeTypes[ext] || 'application/octet-stream';\r"
expect "> "
send "  fs.readFile(filePath, (err, content) => {\r"
expect "> "
send "    if (err) {\r"
expect "> "
send "      res.writeHead(404, { 'Content-Type': 'text/plain' });\r"
expect "> "
send "      res.end('Not Found');\r"
expect "> "
send "    } else {\r"
expect "> "
send "      res.writeHead(200, { 'Content-Type': contentType });\r"
expect "> "
send "      res.end(content);\r"
expect "> "
send "    }\r"
expect "> "
send "  });\r"
expect "> "
send "});\r"
expect "> "
send "server.listen(80, '0.0.0.0', () => {\r"
expect "> "
send "  console.log('Baby Sleep Consulting - EXACT REPLICA DEPLOYED');\r"
expect "> "
send "  console.log('Website: http://31.97.99.104');\r"
expect "> "
send "  console.log('Two-column layout with hero image');\r"
expect "> "
send "  console.log('Success badge overlay');\r"
expect "> "
send "  console.log('Professional styling');\r"
expect "> "
send "});\r"
expect "> "
send "SERVER_EOF\r"
expect "# "

# Start the server
send "node server.js &\r"
expect "# "

# Exit SSH session
send "exit\r"
expect eof
EXPECT_EOF

echo "✅ Final deployment complete!"
echo "🌐 Website: http://31.97.99.104"
echo "🎨 Exact replica with professional two-column design"
echo "🖼️ Hero image with success badge overlay"
echo "📱 Complete responsive layout"